name: Linting
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.12"
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Linting
        run: |
          pip install pylint==3.1.0
          python -m pylint --reports=n --rcfile=.pylintrc certbot_pskz

